version: '3.4'

services:
  demo:
    image: workforce-opt
    build: .
    ports:
      - 8080:8080
    depends_on: 
      - db
   # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: workforceoptimizerDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
  
  
# Volumes
volumes:
  db-data:
 
      